name: Deploy to NuxtHub

on:
  push:
    branches:
      - develop
      - pre-staging
      - staging
      - main

jobs:
  deploy:
    name: Deploy to NuxtHub - ${{ github.ref_name }} by ${{ github.actor }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || github.ref == 'refs/heads/pre-staging' && 'pre-staging' || github.ref == 'refs/heads/develop' && 'development'}}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build
        env:
          API_AUTH: ${{ vars.API_AUTH }}
          API_INVENTORY: ${{ vars.API_INVENTORY }}
          API_STORAGE: ${{ vars.API_STORAGE }}
          DOMAIN: ${{ vars.DOMAIN }}
          API_DO_STORAGE_ENDPOINT: ${{ vars.API_DO_STORAGE_ENDPOINT }}

      # Add this step to remove invalid wrangler.json if it's generated
      - name: Remove invalid wrangler.json
        run: |
          rm -f .output/server/wrangler.json

      - name: Remove Cloudflare deploy config redirect
        run: rm -f .wrangler/deploy/config.json

      - name: Set Wrangler Environment
        id: wrangler-env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then echo "env=production" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then echo "env=staging" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "pre-staging" ]]; then echo "env=pre-staging" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "develop" ]]; then echo "env=development" >> $GITHUB_OUTPUT
          else echo "env=development" >> $GITHUB_OUTPUT
          fi

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --env ${{ steps.wrangler-env.outputs.env }}
